hmcts/et-syr-frontend

charts/et-syr/values.yaml
=> Dummy change

src/main/controllers/ResponseHubController.ts
=> Test- response hub

src/main/controllers/NewSelfAssignmentRequestController.ts, src/main/controllers/RespondentRepliesController.ts, src/main/controllers/SelfAssignmentFormController.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/views/respondent-replies.njk, src/test/unit/controller/NewSelfAssignmentRequestControllerTest.ts, src/test/unit/controller/SelfAssignmentFormController.test.ts
No jira link, it was a bug about new self case assignment link
Update to assign a new case
```
[ ] Yes
[X] No
```
=> Bug_Correction-New self case assignment

package.json, src/main/assets/scss/main.scss, src/main/modules/nunjucks/index.ts, src/main/views/components/hmcts-progress-bar/macro.njk, src/main/views/components/hmcts-progress-bar/template.njk, src/main/views/home.njk, yarn.lock
https://tools.hmcts.net/jira/browse/RET-5394
=> Fix hmcts-progress-bar

src/main/controllers/RespondentEmployeesController.ts, src/main/controllers/RespondentSiteEmployeesController.ts, src/main/controllers/RespondentSitesController.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/respondent-employees.json, src/main/resources/locales/cy/translation/respondent-site-employees.json, src/main/resources/locales/cy/translation/respondent-sites.json, src/main/resources/locales/en/translation/respondent-employees.json, src/main/resources/locales/en/translation/respondent-site-employees.json, src/main/resources/locales/en/translation/respondent-sites.json, src/main/views/respondent-employees.njk, src/main/views/respondent-site-employees.njk, src/main/views/respondent-sites.njk, src/test/unit/controller/RespondentEmployeesController.test.ts, src/test/unit/controller/RespondentSiteEmployeesController.test.ts, src/test/unit/controller/RespondentSitesController.test.ts
https://tools.hmcts.net/jira/browse/RET-3446
https://tools.hmcts.net/jira/browse/RET-3447
https://tools.hmcts.net/jira/browse/RET-3448
Respondent Employees, Respondent Sites & No. of Employees at the site
```
[ ] Yes
[ x] No
```
=> Hearing Preferences - Section 1

src/main/controllers/CaseDetailsController.ts, src/main/controllers/ClaimantAcasCertificateDetailsController.ts, src/main/controllers/ClaimantET1FormController.ts, src/main/controllers/ClaimantET1FormDetailsController.ts, src/main/definitions/constants.ts, src/main/helpers/ResponseHubHelper.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/claimant-acas-certificate-details.json, src/main/resources/locales/cy/translation/claimant-et1-form-details.json, src/main/resources/locales/cy/translation/claimant-et1-form.json, src/main/resources/locales/en/translation/claimant-acas-certificate-details.json, src/main/resources/locales/en/translation/claimant-et1-form-details.json, src/main/resources/locales/en/translation/claimant-et1-form.json, src/main/views/claimant-acas-certificate-details.njk, src/main/views/claimant-et1-form-details.njk, src/main/views/claimant-et1-form.njk, src/main/views/components/case-details/case-details-notification-banner.njk, src/test/unit/controllers/ClaimantAcasCertificateDetailsController.test.ts, src/test/unit/controllers/ClaimantET1FormController.test.ts, src/test/unit/controllers/ClaimantET1FormDetailsController.test.ts, src/test/unit/helpers/RespondentHubHelper.test.ts
https://tools.hmcts.net/jira/browse/RET-3394
* new screens and controllers for ET1 information
* created and updated unit tests
* Todos added where required
```
[ ] Yes
[ x] No
```
=> RET-3394 - ET1 Form & ACAS Cert

src/main/assets/scss/main.scss, src/main/controllers/CaseDetailsController.ts, src/main/controllers/ET3ResponseController.ts, src/main/definitions/constants.ts, src/main/helpers/ResponseHubHelper.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/case-details.json, src/main/resources/locales/cy/translation/et3-response.json, src/main/resources/locales/en/translation/case-details.json, src/main/resources/locales/en/translation/et3-response.json, src/main/views/components/case-details/case-details-notification-banner.njk, src/main/views/et3-response.njk, src/test/unit/controllers/ET3ResponseController.test.ts
https://tools.hmcts.net/jira/browse/RET-4330
* CYA style page, change style as it looks messy when in two-thirds
* controller and unit tests created
* todo for rewiring when view response is available (after submission)
* notification banner updated with placeholder boolean
```
[ ] Yes
[ x] No
```
=> RET-4330 - ET3 Response

src/main/assets/js/go-back.ts, src/main/controllers/ApplicationSubmittedController.ts, src/main/controllers/ResponseSavedController.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/application-submitted.json, src/main/resources/locales/cy/translation/response-saved.json, src/main/resources/locales/en/translation/application-submitted.json, src/main/resources/locales/en/translation/response-saved.json, src/main/views/application-submitted.njk, src/main/views/response-saved.njk, src/test/unit/controllers/AplicationSubmittedController.test.ts, src/test/unit/controllers/ResponseSavedController.test.ts
https://tools.hmcts.net/jira/browse/RET-4323
https://tools.hmcts.net/jira/browse/RET-4333
* RET-4323 & RET-4333
* updated and created unit tests
* navigation to application-submitted.njk from check-your-answers-et3 needs to be done
* updated go-back js to add in the response-saved-button
```
[ ] Yes
[ x] No
```
=> Completed & Response Saved Screens

src/main/controllers/CheckYourAnswersEmployersContractClaimController.ts, src/main/helpers/controller/CheckYourAnswersET3Helper.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/check-your-answers-employers-contract-claim.json, src/main/resources/locales/cy/translation/check-your-answers-et3-common.json, src/main/resources/locales/cy/translation/common.json, src/main/resources/locales/en/translation/check-your-answers-employers-contract-claim.json, src/main/resources/locales/en/translation/check-your-answers-et3-common.json, src/main/resources/locales/en/translation/common.json, src/main/views/check-your-answers-employers-contract-claim.njk, src/main/views/check-your-answers-et3.njk, src/test/unit/controllers/CheckYourAnswersET3Controller.test.ts, src/test/unit/controllers/CheckYourAnswersEmployersContractClaimController.test.ts, src/test/unit/helpers/controller/CheckYourAnswersET3Helper.test.ts
https://tools.hmcts.net/jira/browse/RET-4321
* controller and screen created for ECC CYA
* added to Sonar ignore like other CYA text controllers
* unit tests created/ updated
```
[ ] Yes
[ x] No
```
=> ECC CYA screen

Jenkinsfile_nightly
=> Fix Nightly?

Jenkinsfile_nightly, src/test/java/config/fortify-client.properties
Add Fortify Scanning to et-syr
=> Add Fortify Scanning to et-syr

src/main/controllers/CaseNumberCheckController.ts, src/main/resources/locales/cy/translation/case-number-check.json, src/main/resources/locales/en/translation/case-number-check.json
=> Update to add hint to case number check

package.json, yarn.lock
=> Updates for vulnerabilities

src/main/controllers/CaseNumberCheckController.ts, src/main/controllers/ChangeDetailsController.ts, src/main/controllers/SelfAssignmentCheckController.ts, src/main/controllers/SelfAssignmentFormController.ts, src/main/definitions/constants.ts, src/main/helpers/ErrorHelpers.ts, src/main/helpers/RouterHelpers.ts, src/main/utils/ET3Util.ts, src/test/unit/controllers/CaseNumberCheckController.test.ts, src/test/unit/controllers/ChangeDetailsController.test.ts, src/test/unit/controllers/SelfAssignmentCheckController.test.ts, src/test/unit/controllers/SelfAssignmentFormController.test.ts, src/test/unit/helpers/ErrorHelpers.test.ts
https://tools.hmcts.net/jira/browse/RET-5447
* check if redirect urls are safe before returning to avoid open redirect vulnerabilities
```
[ ] Yes
[ x] No
```
=> Fortify Issues

src/main/controllers/ClaimantEmploymentDatesController.ts, src/main/controllers/ClaimantEmploymentDatesEnterController.ts, src/main/definitions/case.ts, src/main/helpers/ApiFormatter.ts, src/main/helpers/controller/CheckYourAnswersET3Helper.ts, src/main/utils/DateUtil.ts, src/main/utils/ET3DataModelUtil.ts, src/test/unit/utils/DateUtil.test.ts
Bug fixes - date fields
Bug fixes for date fields.
```
[ ] Yes
[X] No
```
=> BugFixes-DateFields

src/main/controllers/ClaimSavedController.ts, src/main/controllers/RespondentSelectPostCodeController.ts, src/main/definitions/constants.ts, src/main/modules/routes/routes.ts, src/main/resources/locales/cy/translation/claim-saved.json, src/main/resources/locales/cy/translation/respondent-select-postcode.json, src/main/resources/locales/en/translation/claim-saved.json, src/main/resources/locales/en/translation/respondent-select-postcode.json, src/main/utils/ET3Util.ts, src/main/utils/NumberUtils.ts, src/main/views/claim-saved.njk, src/test/unit/controllers/ClaimSavedController.test.ts, src/test/unit/controllers/RespondentSelectPostCodeController.test.ts, src/test/unit/helpers/FormHelper.test.ts, src/test/unit/mocks/mockForm.ts, src/test/unit/utils/ET3UtilTest.ts, src/test/unit/utils/NumberUtils.test.ts
Bug fixes for save as draft
-----
Bug fixes for save as draft
-----
```
[ ] Yes
[X] No
```
=> Updates to have save as draft functionality.

src/main/modules/oidc/index.ts, src/main/services/CacheService.ts, src/main/views/home.njk, src/test/unit/services/CacheService.test.ts
Bugfix for existing case links
Bugfix for existing case links
```
[ ] Yes
[X] No
```
=> BugFix-ExistingCaseLinks

src/main/modules/oidc/index.ts, src/main/pcq/index.ts
=> Updates for login screen

src/main/components/form.ts, src/main/controllers/RespondentNameController.ts, src/main/resources/locales/cy/translation/common.json, src/main/resources/locales/cy/translation/respondent-name.json, src/main/resources/locales/en/translation/common.json, src/main/resources/locales/en/translation/respondent-name.json, src/test/unit/components/form.test.ts
https://tools.hmcts.net/jira/browse/RET-3376
ET3 Response Form (LiP): Respondent name
* fix respondent name error
* accessibility hidden error field needed a label
```
[ ] Yes
[ x] No
```
=> Respondent Name

src/main/controllers/SelfAssignmentFormController.ts, src/main/definitions/constants.ts, src/main/resources/locales/cy/translation/common.json, src/main/resources/locales/cy/translation/self-assignment-form.json, src/main/resources/locales/en/translation/self-assignment-form.json, src/main/services/CaseService.ts, src/test/unit/controllers/SelfAssignmentFormController.test.ts, src/test/unit/services/CaseService.test.ts
- Added a check to see if the case is a reform case or not
- If it is a legacy case, redirect user to legacy
- If it is a reform case, validate the user input as before
```
[ ] Yes
[ ] No
```
=> Updates to ET3 reference page

src/main/controllers/ResponseSavedController.ts, src/main/resources/locales/cy/translation/check-your-answers-et3-common.json, src/main/resources/locales/cy/translation/common.json, src/main/resources/locales/cy/translation/response-saved.json, src/main/resources/locales/en/translation/check-your-answers-et3-common.json, src/main/resources/locales/en/translation/common.json, src/main/resources/locales/en/translation/response-saved.json, src/main/views/claimant-notice-period.njk, src/main/views/response-saved.njk, src/test/unit/controllers/ResponseSavedController.test.ts
https://tools.hmcts.net/jira/browse/RET-4333
https://tools.hmcts.net/jira/browse/RET-4306
* update link descriptions and redirectUrls
* fix translations linked to Pay and Pensions
* translations for Weekly, Monthly and Annually fixed
```
[ ] Yes
[ x] No
```
=> Save as draft & CYA Section 4

package.json, src/main/controllers/CaseListController.ts, src/main/resources/locales/en/translation/case-list.json, src/main/services/CaseSelectionService.ts, src/main/utils/ET3Util.ts, src/main/views/case-list.njk, src/test/unit/controllers/CaseListController.test.ts, src/test/unit/mocks/mockApplications.ts, src/test/unit/mocks/mockAxiosResponses.ts, src/test/unit/mocks/mockCaseApiDataResponse.ts, src/test/unit/utils/ET3UtilTest.ts, yarn.lock
Fix for case listing and completion status bugs
Fix for case listing and completion status bugs
-----
```
[ ] Yes
[X] No
```
=> BugFixes-Case Listing, Completion Status

src/main/controllers/AcasEarlyConciliationCertificateController.ts, src/main/controllers/ClaimantET1FormController.ts, src/main/controllers/EmployersContractClaimController.ts, src/main/controllers/EmployersContractClaimDetailsController.ts, src/main/controllers/RespondentContestClaimController.ts, src/main/controllers/RespondentContestClaimReasonController.ts, src/main/controllers/RespondentResponseTaskListController.ts, src/main/definitions/constants.ts, src/main/resources/locales/cy/translation/employers-contract-claim-details.json, src/main/resources/locales/en/translation/employers-contract-claim-details.json, src/main/utils/DocumentUtils.ts, src/main/utils/ET3DataModelUtil.ts, src/main/utils/FileUtils.ts, src/main/utils/NumberUtils.ts, src/main/views/acas-early-conciliation-certificate.njk, src/main/views/claimant-et1-form.njk, src/main/views/respondent-contest-claim-reason.njk, src/main/views/respondent-response-task-list.njk, src/test/unit/controllers/EmployersContractClaimDetailsController.test.ts, src/test/unit/controllers/RespondentContestClaimController.test.ts, src/test/unit/controllers/RespondentContestClaimReasonController.test.ts, src/test/unit/controllers/RespondentResponseTaskListController.test.ts, src/test/unit/utils/DocumentUtils.test.ts, src/test/unit/utils/FileUtils.test.ts, src/test/unit/utils/NumberUtils.test.ts
https://tools.hmcts.net/jira/browse/RET-4314
-----
1. Updates to show pdf files on the pages respondent response tasklist and respondent contest claim.
```
[ ] Yes
[X] No
```
=> BugFixes-File_Updates

src/main/controllers/ApplicationSubmittedController.ts, src/main/controllers/CheckYourAnswersET3Controller.ts, src/main/controllers/RespondentResponseLandingController.ts, src/main/resources/locales/cy/translation/check-your-answers-et3.json, src/main/resources/locales/cy/translation/self-assignment-check.json, src/main/resources/locales/en/translation/check-your-answers-et3.json, src/main/resources/locales/en/translation/self-assignment-check.json, src/main/views/application-submitted.njk, src/main/views/form/main/template.njk, src/main/views/self-assignment-check.njk, src/test/unit/controllers/RespondentResponseLandingController.test.ts
Minor issues within ET3 Process
```
[ ] Yes
[ x] No
```
=> Minor bugs

src/main/resources/locales/cy/translation/sidebar-contact-us.json, src/main/resources/locales/en/translation/sidebar-contact-us.json, src/main/views/components/sidebar/sidebar.njk
Sidebar Contact Us - fix line breaks
```
[ ] Yes
[ x] No
```
=> Sidebar Contact Us

src/main/controllers/RespondToApplicationSubmitController.ts, src/main/definitions/constants.ts, src/main/services/CaseService.ts, src/test/unit/controllers/RespondToApplicationSubmitController.test.ts
=> add response to app logic

src/main/views/contact-tribunal-check-your-answers.njk
https://tools.hmcts.net/jira/browse/RET-5513
Case reference number is removed from the CYA page as per the QA request
```
[ ] Yes
[x] No
```
=> case number ref removed from cya page

src/main/definitions/contact-tribunal-applications.ts
due to the typo, application submission was failing for "Reconsider Judgment" type. It works with the correction/ this I required to test and verify WA too.
```
[ ] Yes
[x] No
```
=> typo bug fix

src/main/resources/locales/cy/translation/appoint-legal-representative.json, src/main/resources/locales/cy/translation/case-details.json, src/main/resources/locales/cy/translation/contact-tribunal.json
=> Welsh translations noc
